In [1]:
import nltk
nltk.download('brown')
from nltk.corpus import brown
X=brown.sents()

[nltk_data] Downloading package brown to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package brown is already up-to-date!


In [2]:
nltk.download('averaged_perceptron_tagger')

[nltk_data] Downloading package averaged_perceptron_tagger to
[nltk_data]     C:\Users\user\AppData\Roaming\nltk_data...
[nltk_data]   Package averaged_perceptron_tagger is already up-to-
[nltk_data]       date!


True

In [3]:
from string import punctuation
li=["''",":","$","``"]
stoplist = set(list(punctuation)+li)
X1=[]
X2=[]
for i in range(len(X)):
  X1.append([token.lower() for token in X[i] if token not in stoplist])
  X2.append(nltk.pos_tag(X1[i]))

In [7]:
s="i good play badly"
x=s.split()
print(x)
s1=nltk.pos_tag(x)
print(s1)

['i', 'good', 'play', 'badly']
[('i', 'RB'), ('good', 'JJ'), ('play', 'NN'), ('badly', 'RB')]


In [222]:
print(X2[2])

[('the', 'DT'), ('september-october', 'JJ'), ('term', 'NN'), ('jury', 'NN'), ('had', 'VBD'), ('been', 'VBN'), ('charged', 'VBN'), ('by', 'IN'), ('fulton', 'JJ'), ('superior', 'JJ'), ('court', 'NN'), ('judge', 'NN'), ('durwood', 'NN'), ('pye', 'NN'), ('to', 'TO'), ('investigate', 'VB'), ('reports', 'NNS'), ('of', 'IN'), ('possible', 'JJ'), ('irregularities', 'NNS'), ('in', 'IN'), ('the', 'DT'), ('hard-fought', 'JJ'), ('primary', 'NN'), ('which', 'WDT'), ('was', 'VBD'), ('won', 'VBN'), ('by', 'IN'), ('mayor-nominate', 'JJ'), ('ivan', 'NN'), ('allen', 'NN'), ('jr.', 'NN')]


In [12]:
t2=['VBP', 'VBG','VBD','VB','VBZ','VBN']
t1=['NNP','NNS','NN','NNPS']
t3=['JJ', 'JJS','JJR']
t4=['RBS','RBR', 'RB','RP']
t5=['PRP$', 'PDT','PRP']
t6=['DT']
t7=['TO', 'CD','IN','UH', '$', 'MD', 'WP']
t8=['POS', 'WDT', 'EX']

In [20]:
for i in X2:
    for j in range(len(i)):
        if i[j][1] in t1:
             i[j]=( i[j][0],'NN')
        elif i[j][1] in t2:
             i[j]=( i[j][0],'VB')
        elif i[j][1] in t3:
             i[j]=( i[j][0],'ADJ')
        elif i[j][1] in t4:
             i[j]=( i[j][0],'ADV')
        elif i[j][1] in t5:
            i[j]=( i[j][0],'PRO')
        elif i[j][1] in t6:
             i[j]=( i[j][0],'DT')
        elif i[j][1] in t7:
             i[j]=( i[j][0],'PRE')
        elif i[j][1] in t8:
             i[j]=( i[j][0],'ADP')
        else:
             i[j]=( i[j][0],'OTHER')

In [21]:
tags=dict({})
taglist1=[]
pie=[]
for i in range(len(X2)):
    for j in range(len(X2[i])):
        taglist1.append(X2[i][j][1])
taglist=set(taglist1)
print(taglist)
j=0
for i in taglist:
    tags[i]=j
    j+=1

{'VB', 'PRO', 'NN', 'ADP', 'ADV', 'OTHER', 'DT', 'PRE', 'ADJ'}


In [23]:
for i in taglist:
    c=0
    for j in range(len(X2)):
        if(X2[j][0][1]==i):
            c+=1
    pie.append(c)

In [24]:
piei=[]
for i in pie:
    piei.append(float(i/sum(pie)))
print(piei)

[0.04263247205360111, 0.16323495967671395, 0.19852002169235344, 0.015587005580532862, 0.08937599496177598, 0.07193464303832899, 0.20268355404719837, 0.16470444168430629, 0.05132690726518902]


In [25]:
def sumation(A,n):
    s=0
    for i in range(n):
        s=s+A[i]
    return s

In [26]:
import numpy as np
n=len(pie)
A=[[0 for i in range(n+1)]for i in range(n+1)]
A1=[[0 for i in range(n)]for i in range(n)]
A[0][0]=1
for i in range(1,n+1):
    A[0][i]=0
k=0
for i in range(1,n+1):
    A[i][0]=pie[k]
    k+=1
for i in range(len(X2)):
    for j in range(len(X2[i])-1):
        k=tags[X2[i][j][1]]
        l=tags[X2[i][j+1][1]]
        A1[k][l]=A1[k][l]+1
for i in range(n):
    for j in range(n):
        A[i+1][j+1]=A1[i][j]
for i in range(1,n+1):
    z=sumation(A[i],n+1)
    for j in range(n+1):
        if(z!=0):
          A[i][j]=A[i][j]/z
print(A)

[[1, 0, 0, 0, 0, 0, 0, 0, 0, 0], [0.014898546826187697, 0.1539068183624437, 0.08931180573811082, 0.08973974922511661, 0.002194738740501183, 0.12429312906164221, 0.027180524903254205, 0.1627102272379916, 0.25476698477132537, 0.08099747513342667], [0.1453245701470222, 0.3669791926239721, 0.0074134064291054074, 0.20154809369548965, 0.001354971343134812, 0.04186394218788936, 0.017505606777971593, 0.030074134064291054, 0.1177890605532021, 0.07014702217792175], [0.046106278465995194, 0.19457434576458496, 0.022943439768899794, 0.16935565785143442, 0.01702373165073316, 0.03587578770309637, 0.10957351286124643, 0.02357319595168348, 0.362061049783242, 0.018913000199084214], [0.10237849017580145, 0.5710674480064346, 0.06319659887395151, 0.05526829828794669, 0.0029874755831322533, 0.027691600597495116, 0.002872572676088705, 0.047110191887854765, 0.10835344134206595, 0.019073882569229], [0.09078147766445148, 0.24355876186076264, 0.036923842354028215, 0.03418742670315221, 0.003998009879526636, 0.099

In [56]:
s="i am sick"
s1=s.split()

In [57]:
taglist=list(taglist)
B=[[0 for i in range(n+1)]for i in range(len(s1))]
B1=[[0 for i in range(n)]for i in range(len(s1))]
B[0][0]=1
for i in range(1,len(s1)):
    B[i][0]=0
l1=[]
for k in range(len(taglist)):
  c=0
  for l in range(len(s1)):
   for i in range(len(X2)):
    for j in range(len(X2[i])):
        if(X2[i][j][1]==taglist[k] and X2[i][j][0]==s1[l]):
                    B1[l][k]=B1[l][k]+1
        if(X2[i][j][1]==taglist[k]):
            c+=1
  l1.append(c)
for i in range(len(s1)):
    for j in range(n):
        B[i][j+1]=B1[i][j]
B=np.array(B)
B=B.transpose()
print(B)

[[   1    0    0]
 [ 658  237    2]
 [   0    0    0]
 [3567    0    5]
 [   1    0    0]
 [ 137    0    1]
 [   0    0    0]
 [   0    0    0]
 [   0    0    0]
 [ 801    0   43]]


In [58]:
B2=[[0 for i in range(len(s1))]for i in range(n+1)]
B2[0]=B[0]
for i in range(1,n+1):
    z=sum(B[i])
    for j in range(len(s1)):
        if(sum(B[i])!=0):
          B2[i][j]=B[i][j]/z

In [59]:
print(B2)

[array([1, 0, 0]), [0.7335562987736901, 0.26421404682274247, 0.002229654403567447], [0, 0, 0], [0.9986002239641657, 0.0, 0.0013997760358342665], [1.0, 0.0, 0.0], [0.9927536231884058, 0.0, 0.007246376811594203], [0, 0, 0], [0, 0, 0], [0, 0, 0], [0.9490521327014217, 0.0, 0.0509478672985782]]


In [60]:
B3=[[0 for i in range(len(s1))]for i in range(n+1)]
for i in range(n+1):
    B3[i]=B2[i][::-1]

In [61]:
M=[[0 for i in range(n+1)]for i in range(len(s1)+1)]
M[0][0]=0
for i in range(1,n+1):
    M[0][i]=piei[i-1]
for i in range(1,len(s1)+1):
    for j in range(n+1):
         z=0
         for k in range(n+1):
            z= z+M[i-1][k]*A[i][k]
         M[i][j]=z*B3[j][i-1]
print(M)

[[0, 0.04263247205360111, 0.16323495967671395, 0.19852002169235344, 0.015587005580532862, 0.08937599496177598, 0.07193464303832899, 0.20268355404719837, 0.16470444168430629, 0.05132690726518902], [0.0, 0.0002924212217610175, 0.0, 0.00018358191203781681, 0.0, 0.0009503689707233068, 0.0, 0.0, 0.0, 0.006681859564303439], [0.0, 0.00017248205567451825, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0], [3.356058313900011e-05, 2.4618577152131633e-05, 0.0, 3.3513605838973514e-05, 3.356058313900011e-05, 3.331739050755808e-05, 0.0, 0.0, 0.0, 3.185074300277143e-05]]


In [67]:
print(taglist)

['VB', 'PRO', 'NN', 'ADP', 'ADV', 'OTHER', 'DT', 'PRE', 'ADJ']


In [68]:
tag=[]
for i in range(len(s1)):
    z=max(M[i])
    for j in range(n):
        if(M[i][j]==z):
            break
    tag.append(j)
print(tag)
final_tag=[]
print("tags for input sequence")
for i in tag:
    final_tag.append(taglist[i])
print(final_tag)

[7, 8, 1]
tags for input sequence
['PRE', 'ADJ', 'PRO']
